language: java
jdk:
- oraclejdk8
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
- mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn -Psyscall clean compile
after_success:
  - mvn coveralls:report

group: stable