spring:
  thymeleaf:
    prefix: classpath:/templates/ 
    cache: false
  h2.console:
    enabled: true
    path: /db
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create-drop
  datasource:
    url: jdbc:h2:~/dev;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS SYSCALL
    platform: h2
  devtools:
    remote:
      debug:
        enabled: true
  mail:
    host: smtp.gmail.com
    username: syscall.remember@gmail.com
    password: tads12345
    port: 587
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com
      
Configutation:
  status: warn

  Appenders:
    Console:
      name: CONSOLE
      target: SYSTEM_OUT
      PatternLayout:
        Pattern: "%d{ISO8601} %-5p [%c{3}] [%t] %m%n"
    RollingFile:
      - name: APPLICATION
        fileName: ../logs/syscall.log
        filePattern: "../logs/$${date:yyyy-MM}/syscall-%d{yyyy-MM-dd}-%i.log.gz"
        PatternLayout:
          Pattern: "%d{ISO8601} %-5p [%c{3}] [%t] %m%n"
        policies:
          TimeBasedTriggeringPolicy:
            interval: 1
            modulate: true

  Loggers:
      Root:
        level: info
        AppenderRef:
          - ref: CONSOLE
          - ref: APPLICATION
      Logger:
        - name: com.syscall
          additivity: false
          level: info
          AppenderRef:
            - ref: CONSOLE
            - ref: APPLICATION
        - name: com.syscall
          additivity: false
          level: debug
          AppenderRef:
            - ref: CONSOLE
            - ref: APPLICATION