spring:
  thymeleaf:
    prefix: classpath:/templates/ 
    cache: false
  h2.console:
    enabled: true
    path: /db
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create-drop
  datasource:
    url: jdbc:h2:~/dev;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS SYSCALL
    platform: h2
  devtools:
    remote:
      debug:
        enabled: true
  mail:
    host: smtp.gmail.com
    username: syscall.remember@gmail.com
    password: tads12345
    port: 587
    protocol: smtp
    tls: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true
      ssl.trust: smtp.gmail.com

